amazon:
  base_url: "https://www.amazon.com"
  categories:
    laptops: "/s?k=laptops"
    monitors: "/s?k=monitors"
    gpus: "/s?k=gpu"
    ram: "/s?k=RAM"
    gadgets: "/s?k=gadgets"
  max_pages: 20
  delay: 1